"use strict";
const test=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm");
const L=require("../web/js/aprendizaje.js");
function setup(){let now=new Date(2026,8,21,12).getTime();let state={esmeraldas:70,esmeraldasGanadasTotal:120,diagnostico:{hecho:true,resultados:{viejo:1}},premios:[{id:"r1"}]};return {state,get now(){return now;},advance(n){now=L.addDays(now,n);},engine(){return L.create(state,()=>{},()=>now);}};}
test("No transforma historial ni premios en evidencia nueva",()=>{const s=setup(),E=s.engine();assert.equal(E.summary("lectura").n,0);assert.equal(s.state.esmeraldas,70);assert.equal(s.state.diagnostico.resultados.viejo,1);assert.deepEqual(s.state.premios,[{id:"r1"}]);});
test("Pausa por respuesta, restauración y recompensa única",()=>{const s=setup();let E=s.engine(),c=E.start();E.answer(true,false,"adulto");E=s.engine();assert.equal(E.start().cursor,1);assert.equal(E.start().id,c.id);while(!c.completed)E.answer(true,false,"objetiva");assert.equal(E.rewardCycle(c),15);assert.equal(E.rewardCycle(c),0);assert.equal(s.state.esmeraldas,85);assert.equal(E.data.cycles.length,1);});
test("Chequeo semanal, revisión de 28 días y ausencia sin borrar historia",()=>{const s=setup(),E=s.engine();const c=E.start();while(!c.completed)E.answer(null,false,"sin-verificar");assert.equal(E.due(),null);s.advance(6);assert.equal(E.due(),null);s.advance(1);assert.equal(E.due(),"semanal");let weekly=E.start();assert.equal(weekly.questions.length,6);while(!weekly.completed)E.answer(true,false,"objetiva");s.advance(21);assert.equal(E.due(),"revision");E.start();assert.equal(E.data.cycles.length,3);assert.equal(E.data.cycles[0].id,c.id);});
test("Ayuda y micrófono incierto no certifican respuesta independiente",()=>{const s=setup(),E=s.engine(),q=E.generate("lectura",1,"test",0);E.record(q,true,true,"adulto","chequeo","a");E.record(q,false,false,"automatico","chequeo","b");E.record(q,null,false,"sin-verificar","chequeo","c");const r=E.summary("lectura");assert.equal(r.n,0);assert.equal(r.status,"Por observar");assert.equal(r.pending,1);});
test("Repetir el mismo día no simula retención ni transferencia",()=>{const s=setup(),E=s.engine();for(let i=0;i<12;i++){const q=E.generate("dictado",1,"x",i);q.fresh=true;E.record(q,true,false,"objetiva","transferencia","q"+i);}assert.notEqual(E.summary("dictado").status,"Consolidando");assert.notEqual(E.summary("dictado").status,"Transferencia observada");});
test("Evidencia repetida con mismo id se guarda una sola vez",()=>{const E=setup().engine(),q=E.generate("operaciones",1,"x",0);E.record(q,true,false,"objetiva","chequeo","unique");E.record(q,false,false,"objetiva","chequeo","unique");assert.equal(E.data.events.length,1);assert.equal(E.data.events[0].result,true);});
test("Dos dificultades ajustan la próxima pregunta del mismo objetivo",()=>{const E=setup().engine(),c=E.start();E.answer(false,false,"adulto");E.answer(false,false,"adulto");assert.equal(c.questions[2].skill,"lectura");assert.equal(c.questions[2].level,0);});
test("Cambiar evidencia cambia prioridad y no la misión ya iniciada",()=>{const s=setup(),E=s.engine();E.data.settings.task="";for(const k of ["lectura","dictado","escucha","comprension"]){for(let i=0;i<3;i++)E.record(E.generate(k,1,"s",i),k!=="comprension",false,"objetiva","chequeo",k+i);}assert.equal(E.priorities("reading")[0],"comprension");const m=E.mission();E.data.settings.reading=["dictado"];assert.equal(E.mission().id,m.id);assert.equal(E.mission().steps[1].skill,"comprension");s.advance(1);assert.equal(E.mission().steps[1].skill,"dictado");});
test("La misión paga una sola vez y conserva edificios después de ausencia",()=>{const s=setup(),E=s.engine(),m=E.mission();assert.equal(E.build("garden"),false);m.steps.forEach((_,i)=>E.finishPractice(i));assert.equal(E.build("garden"),true);assert.equal(E.build("library"),false);assert.equal(s.state.esmeraldas,90);s.advance(30);E.mission();assert.equal(E.data.buildings.length,1);});
test("Revisiones de aciertos siguen programadas y sin castigo",()=>{const s=setup(),E=s.engine(),q=E.generate("operaciones",1,"r",0);E.record(q,true,false,"objetiva","chequeo","r");assert.ok(E.data.reviews.operaciones.due>s.now);s.advance(10);assert.equal(E.mission().steps[0].skill,"operaciones");assert.equal(s.state.esmeraldas,70);});
test("Pregunta nueva de transferencia no reutiliza las de enseñanza",()=>{const E=setup().engine(),m=E.mission();const previous=new Set(m.steps.slice(0,3).flatMap(s=>s.questions.map(q=>q.key)));for(const q of m.steps[3].questions)assert.equal(previous.has(q.key),false);});
test("Gráficas y operaciones generadas tienen respuesta numérica válida",()=>{const E=setup().engine();for(let n=0;n<120;n++)for(let level=0;level<3;level++){const q=E.generate("graficas",level,"g",n);const [a,b]=q.graph.map(x=>x.value);assert.equal(q.answer,level===0?a:level===1?a+b:Math.abs(a-b));assert.ok(Number.isInteger(E.generate("operaciones",level,"o",n).answer));}});
test("Fecha local no cambia por medianoche UTC; revisión respeta cambio horario",()=>{const t=new Date(2026,8,21,23,30);assert.equal(L.day(t),"2026-09-21");const end=new Date(2026,9,31,12);assert.equal(new Date(L.addDays(end,1)).getHours(),12);});
function core(){const entries=new Map([["gaby.local",JSON.stringify({esmeraldas:777})],["gaby.prueba",JSON.stringify({version:2,esmeraldas:30,esmeraldasGanadasTotal:50,palabras:{made:{verde:2,ultima:"verde"}},jugador:{nombre:"Test"}})]]);const storage={getItem:k=>entries.get(k)||null,setItem:(k,v)=>entries.set(k,String(v)),removeItem:k=>entries.delete(k)};const w={DATOS:{PREMIOS_INICIALES:[]},CONFIG:{}};const ctx={window:w,localStorage:storage,location:{search:"?prueba",hash:""},console,setTimeout,clearTimeout,Date,Set};vm.runInNewContext(fs.readFileSync("web/js/nucleo.js","utf8"),ctx);return {N:w.NUCLEO,entries};}
test("Respaldo por perfil es restaurable; prueba no toca partida real",()=>{const {N,entries}=core();N.Almacen.respaldarAprendizaje();const before=N.Almacen.respaldoAprendizaje();L.create(N.Almacen.leer(),N.Almacen.guardar).start();assert.equal(JSON.parse(before).aprendizaje,undefined);N.Almacen.respaldarAprendizaje();assert.equal(N.Almacen.respaldoAprendizaje(),before);assert.equal(JSON.parse(entries.get("gaby.local")).esmeraldas,777);N.Almacen.importar(before);assert.equal(N.Almacen.leer().esmeraldas,30);assert.equal(N.Almacen.leer().aprendizaje,undefined);});
test("Sopa y letras móviles no cuentan como lectura oral observada",()=>{const {N}=core();N.Progreso.registrarPalabra("made","verde",null,"reconocimiento-visual");N.Progreso.registrarPalabra("made","verde",null,"letras-moviles");assert.equal(N.Progreso.dominadas().length,0);assert.equal(N.Almacen.leer().palabras.made.observaciones.length,2);});


test("No mezcla porcentajes de dificultades distintas",()=>{const E=setup().engine();for(let i=0;i<5;i++)E.record(E.generate("operaciones",0,"simple",i),true,false,"objetiva","chequeo","easy"+i);E.record(E.generate("operaciones",2,"hard",0),false,false,"objetiva","chequeo","hard");assert.equal(E.summary("operaciones").referenceLevel,2);assert.equal(E.summary("operaciones").n,1);assert.equal(E.summary("operaciones").pct,0);});
test("No llama nueva a una palabra vista en la práctica",()=>{const E=setup().engine(),m=E.mission();E.expose(1);const q={...m.steps[1].questions[0],fresh:true};E.record(q,true,false,"objetiva","transferencia","reused");assert.equal(E.data.events[0].fresh,false);});
test("Diagnóstico terminado con omisiones conserva ruta provisional",()=>{const E=setup().engine(),c=E.start();while(!c.completed)E.answer(null,false,"sin-verificar");assert.equal(E.mission().provisional,true);assert.equal(E.summary("dictado").n,0);});
test("Pruebas de banco: opciones únicas y respuesta presente",()=>{const E=setup().engine();for(let i=0;i<40;i++)for(const k of ["comprension","escucha"]){const q=E.generate(k,1,"stories",i);assert.ok(q.options.includes(q.answer));assert.equal(new Set(q.options).size,q.options.length);}});

test("La tarea cargada prioriza su habilidad en la próxima misión",()=>{const s=setup(),E=s.engine();E.setTask({title:"Lectura de hoy",skill:"lectura",notes:"leer palabras"});assert.equal(E.data.task.skill,"lectura");assert.equal(E.priorities("reading")[0],"lectura");assert.equal(E.mission().task.skill,"lectura");});
